---
version: "3.7"

networks:
  openproject:
  stack:

volumes:
  op-pg-data:
  op-assets-data:

x-op-app: &op-app
  image: &op-image openproject/community:10.4.0
  restart: unless-stopped
  environment:
    - "RAILS_CACHE_STORE=memcache"
    - "OPENPROJECT_CACHE__MEMCACHE__SERVER=op-cache:11211"
    - "OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    - "DATABASE_URL=postgres://postgres:p4ssw0rd@op-db/openproject"
    - "USE_PUMA=true"
    # set to true to enable the email receiving feature. See ./docker/cron for more options
    - "IMAP_ENABLED=false"
  volumes:
    - "op-assets-data:/var/openproject/assets"
  depends_on:
    - op-db
    - op-cache

services:
  ## SSL and general security
  # Don't start this section if you're developing locally and just connect to stack-nginx on localhost:8080
  public-nginx:
    image: nginx:1.17.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/public-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/public-certbot/conf:/etc/letsencrypt
      - ./data/public-certbot/www:/var/www/certbot
    networks:
      - stack
    depends_on:
      - stack-nginx

  public-certbot:
    image: certbot/certbot:v1.3.0
    volumes:
      - ./data/public-certbot/conf:/etc/letsencrypt
      - ./data/public-certbot/www:/var/www/certbot

  ## Reverse proxy which serves all applications
  stack-nginx:
    image: nginx:1.17.9
    ports:
      - "8080:80"
    volumes:
      - ./config/stack-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - stack
      - openproject
    depends_on:
      - op-proxy

  ## OpenProject stack (https://github.com/opf/openproject/blob/dev/docker-compose.yml)
  op-db:
    image: postgres:10
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "op-pg-data:/var/lib/postgresql/data"
      # For dumping DB state to
      - "./share/op-db:/share"
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=openproject
    networks:
      - openproject

  op-cache:
    image: memcached
    restart: unless-stopped
    networks:
      - openproject

  op-proxy:
    image: *op-image
    command: "./docker/proxy"
    environment:
      - APP_HOST=op-web
      - "OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    depends_on:
      - op-web
    networks:
      - openproject

  op-web:
    <<: *op-app
    command: "./docker/web"
    networks:
      - openproject

  op-worker:
    <<: *op-app
    command: "./docker/worker"
    networks:
      - openproject

  op-cron:
    <<: *op-app
    command: "./docker/cron"
    networks:
      - openproject

  op-seeder:
    <<: *op-app
    command: "./docker/seeder"
    restart: on-failure
    networks:
      - openproject
