---
# Adding SSL termination to our stack
version: "3.7"

services:
  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: >
      certonly
        --webroot
        -w /var/www/certbot
        --email admin@bcc3d.ca
        --agree-tos
        --no-eff-email
        -d track.bcc3d.ca -d qa.track.bcc3d.ca
    depends_on:
      - nginx
