#!/bin/bash
set -e
bash ./scripts/apply_openproject_sql_dump {{ openproject.initFile }}

echo 'Setting OpenProject hostname to {{ apps.openproject.hostname }}'
cat << EOF | docker-compose exec -T -u postgres op-db psql openproject
UPDATE public.settings
SET value='{{ apps.openproject.hostname }}'
WHERE name='host_name';
EOF

echo 'Setting OpenProject scheme to {{ scheme }}'
cat << EOF | docker-compose exec -T -u postgres op-db psql openproject
UPDATE public.settings
SET value='{{ scheme }}'
WHERE name='protocol';
EOF

docker-compose up -d
