{% raw %}
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
{% endraw %}

title: BC Covid-19 3D Printing Group

email: admin@bcc3d.ca
description: >- # this means to ignore newlines until "baseurl:"
  We're a grassroots, volunteer-based organization that's trying to help stem the shortage of PPE
  for our medical professionals currently involved in the front-line fight against COVID-19 in BC.
  Our guiding principle is to pair our 3D printers and digital fabrication volunteers with
  immediate demand from healthcare professionals.

baseurl: "" # the subpath of your site, e.g. /blog
url: "{{ scheme }}://{{ apps.bcc3d_ca.hostname }}"
# twitter_username: jekyllrb
# github_username:  jekyll
google_analytics_key: "{{ apps.bcc3d_ca.google_analytics_key }}"

endpoints:
  hcp_submit: "{{ scheme }}://{{ apps.bcc3d_ca.hostname }}/api/hcp/submit"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
