---
version: "3.7"
services:
  jekyll-build:
    build:
      dockerfile: build.Dockerfile
      context: .
    volumes:
      - .:/build
    environment:
      - JEKYLL_ENV={{ apps.bcc3d_ca.jekyll_environment|default('development', true) }}