---
version: "3.7"
services:
  jekyll-build:
    build:
      dockerfile: build.Dockerfile
      context: .
    volumes:
      - .:/build
    environment:
      - JEKYLL_ENV={{ 'production' if apps.bcc3d_ca.production else 'development'}}